org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)
neo_version=21.1.192
neo_version_range=[21,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_id=initial_house
mod_name=Initial House
mod_license=LGPL v2.1
mod_version=4.1.0
mod_authors=Liu Dongyu
mod_description=This mod adds an initial house at the spawn point in the overworld.
